name: My awesome workflow
description: lorem ipsum dolor sit ahmet

maintainer: Anthony-Jhoiro

parameters:
  git_repo:
    type: string

  output:
    type: string

imports:
  - name: git_workflow
    url: https://example.com/file.yaml
---

workflow:
  steps:
    - name: Git Clone Repository
      image: alpine/git:v2.32.0
      workdir: /app
      commands: |
        echo Hello World !
        git clone {{ index .Parameters "git_repo" }} .
      persist:
        - name: "{{ index .Parameters "output" }}"
          source: /app


