name: My awesome workflow
description: lorem ipsum dolor sit ahmet

maintainer: Anthony-Jhoiro

parameters:
  git_repo:
    type: string

  output:
    type: string

imports:
  - name: hello
    url: https://raw.githubusercontent.com/Anthony-Jhoiro/sample_git/master/test_action.yml

  - name: fail
    url: https://raw.githubusercontent.com/Anthony-Jhoiro/WorkiGo/master/examples/failing-step.yaml
---

workflow:
  steps:
    - name: GitCloneRepository
      image: alpine/git:v2.32.0
      workdir: /app
      commands: |
        echo Hello World !
        git clone {{ index .Parameters "git_repo" }} .
      persist:
        - name: "{{ index .Parameters "output" }}"
          source: /app

    - name: Execute Python code
      depends_on:
        - GitCloneRepository
      image: python:slim
      workdir: /app
      commands: |
        python3 script.py
      persist:
        - name: "{{ index .Parameters "output" }}"
          source: /app

    - name: Say hello
      workflow: hello
      parameters:
        name: Anthony




